### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by RoderickQiu** [omar2535/vuepress-sidebar-children-autogenerator#1]
https://github.com/omar2535/vuepress-sidebar-children-autogenerator/blob/3ab181352cfdd205f802030d84b46ac2ea163325/index.js#L18

In this line, it is defined that filesToExclude's members must all use lower cases and that all the file names processed will be generated into lower case forms, which is something not mentioned in the README file. Because this problem, I wasted nearly an hour checking all the stuff so I hope others won't waste another hour checking it.

Hope a tip concerning it will be included in README.md in this proj.

**Comment by omar2535** [comment]
Hey, thanks for the suggestion. I have changed it in the latest version and also disabled casing checks so now the files should be excluded regardless of casing.
